sonar.organization=sflotron
sonar.projectKey=youtrack-api-client
sonar.sources=client,.github/workflows

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=coverage.xml
sonar.test.inclusions=**/*_test.go
sonar.tests=.